# VTU Viva Questions and Answers for Data Science and Its Applications Laboratory (21AD62)

## Overview
This repository contains a collection of viva questions and answers for the Data Science and Its Applications Laboratory (21AD62) course offered by Visvesvaraya Technological University (VTU).

## Modules Covered
1. Introduction to Python/R and Basic Data Visualization
2. Data Cleaning and Manipulation
3. Supervised Learning Techniques
4. Decision Trees and Clustering Methods
5. Web Scraping Project with OpenAI

## Purpose of Learning
- Gain practical knowledge of Python/R programming for data analysis.
- Learn data cleaning techniques to improve data quality.
- Understand supervised learning algorithms for classification and regression.
- Explore decision trees, clustering methods, and their applications.
- Implement a web scraping project using OpenAI for data extraction from Instagram.

## Connect with Me
- LinkedIn: [Farha Kousar](https://www.linkedin.com/in/farhakousar16)
- GitHub: [FarhaKousar1601](https://github.com/FarhaKousar1601)
- Personal Bio: [Farha's Bio](https://farhakousar1601.bio.link)

Feel free to follow me and connect on LinkedIn to stay updated with my projects and activities. You can also explore my GitHub profile for more projects and collaborations.
